coredata:
  inputs: ../Resources/Calculator.xcdatamodeld
  outputs:
  - templatePath: Templates/CoreData.stencil
    output: ../SupportingFiles/Generated/CoreData+Generated.swift
    
fonts:
  inputs: ../Resources/Calculator.xcdatamodeld
  outputs:
  - templatePath: Templates/Fonts.stencil
    output: ../SupportingFiles/Generated/Fonts+Generated.swift
    
strings:
  inputs: ../Resources/Fonts
  outputs:
  - templatePath: Templates/Strings.stencil
    output: ../SupportingFiles/Generated/Strings+Generated.swift
    
xcassets:
  inputs: ../Resources/Assets.xcassets
  outputs:
  - templatePath: Templates/Assets.stencil
    output: ../SupportingFiles/Generated/Assets+Generated.swift
