coredata:
  inputs: ../../Calculator/Resources/Calculator.xcdatamodeld
  outputs:
  - templatePath: Templates/CoreData.stencil
    output: ../../Calculator/SupportingFiles/Generated/CoreData+Generated.swift
    
fonts:
  inputs: ../../Calculator/Resources/Calculator.xcdatamodeld
  outputs:
  - templatePath: Templates/Fonts.stencil
    output: ../../Calculator/SupportingFiles/Generated/Fonts+Generated.swift
    
strings:
  inputs: ../../Calculator/Resources/Fonts
  outputs:
  - templatePath: Templates/Strings.stencil
    output: ../../Calculator/SupportingFiles/Generated/Strings+Generated.swift
    
xcassets:
  inputs: ../../Calculator/Resources/Assets.xcassets
  outputs:
  - templatePath: Templates/Assets.stencil
    output: ../../Calculator/SupportingFiles/Generated/Assets+Generated.swift
